/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedCrashRouteImport } from './routes/_authenticated/crash'
import { Route as AuthenticatedFishRouteImport } from './routes/_authenticated/fish'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedInvestidorIndexRouteImport } from './routes/_authenticated/investidor.index'
import { Route as ApiPublicWebhooksNetshopRouteImport } from './routes/api/public/webhooks/netshop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrashRoute = AuthenticatedCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFishRoute = AuthenticatedFishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestidorIndexRoute =
  AuthenticatedInvestidorIndexRouteImport.update({
    id: '/investidor/',
    path: '/investidor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksNetshopRoute =
  ApiPublicWebhooksNetshopRouteImport.update({
    id: '/api/public/webhooks/netshop',
    path: '/api/public/webhooks/netshop',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/fish': typeof AuthenticatedFishRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/investidor/': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/fish': typeof AuthenticatedFishRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/investidor': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/crash': typeof AuthenticatedCrashRoute
  '/_authenticated/fish': typeof AuthenticatedFishRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/investidor/': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/carteira'
    | '/crash'
    | '/fish'
    | '/kyc'
    | '/investidor/'
    | '/api/public/webhooks/netshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/carteira'
    | '/crash'
    | '/fish'
    | '/kyc'
    | '/investidor'
    | '/api/public/webhooks/netshop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/_authenticated/carteira'
    | '/_authenticated/crash'
    | '/_authenticated/fish'
    | '/_authenticated/kyc'
    | '/_authenticated/investidor/'
    | '/api/public/webhooks/netshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmpresasRoute: typeof EmpresasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  PagamentosRoute: typeof PagamentosRoute
  ApiPublicWebhooksNetshopRoute: typeof ApiPublicWebhooksNetshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crash': {
      id: '/_authenticated/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof AuthenticatedCrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fish': {
      id: '/_authenticated/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof AuthenticatedFishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investidor/': {
      id: '/_authenticated/investidor/'
      path: '/investidor'
      fullPath: '/investidor/'
      preLoaderRoute: typeof AuthenticatedInvestidorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/netshop': {
      id: '/api/public/webhooks/netshop'
      path: '/api/public/webhooks/netshop'
      fullPath: '/api/public/webhooks/netshop'
      preLoaderRoute: typeof ApiPublicWebhooksNetshopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedCrashRoute: typeof AuthenticatedCrashRoute
  AuthenticatedFishRoute: typeof AuthenticatedFishRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedInvestidorIndexRoute: typeof AuthenticatedInvestidorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedCrashRoute: AuthenticatedCrashRoute,
  AuthenticatedFishRoute: AuthenticatedFishRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedInvestidorIndexRoute: AuthenticatedInvestidorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmpresasRoute: EmpresasRoute,
  InvestimentosRoute: InvestimentosRoute,
  PagamentosRoute: PagamentosRoute,
  ApiPublicWebhooksNetshopRoute: ApiPublicWebhooksNetshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
