/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DesportosRouteImport } from './routes/desportos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedCrashRouteImport } from './routes/_authenticated/crash'
import { Route as AuthenticatedFishRouteImport } from './routes/_authenticated/fish'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedInvestidorIndexRouteImport } from './routes/_authenticated/investidor.index'
import { Route as AuthenticatedInvestidorExtratoRouteImport } from './routes/_authenticated/investidor.extrato'
import { Route as AuthenticatedInvestidorOrdensRouteImport } from './routes/_authenticated/investidor.ordens'
import { Route as AuthenticatedInvestidorRendimentosRouteImport } from './routes/_authenticated/investidor.rendimentos'
import { Route as ApiPublicCronSportsSyncRouteImport } from './routes/api/public/cron/sports-sync'
import { Route as ApiPublicWebhooksNetshopRouteImport } from './routes/api/public/webhooks/netshop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DesportosRoute = DesportosRouteImport.update({
  id: '/desportos',
  path: '/desportos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrashRoute = AuthenticatedCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFishRoute = AuthenticatedFishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestidorIndexRoute =
  AuthenticatedInvestidorIndexRouteImport.update({
    id: '/investidor/',
    path: '/investidor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestidorExtratoRoute =
  AuthenticatedInvestidorExtratoRouteImport.update({
    id: '/investidor/extrato',
    path: '/investidor/extrato',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestidorOrdensRoute =
  AuthenticatedInvestidorOrdensRouteImport.update({
    id: '/investidor/ordens',
    path: '/investidor/ordens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestidorRendimentosRoute =
  AuthenticatedInvestidorRendimentosRouteImport.update({
    id: '/investidor/rendimentos',
    path: '/investidor/rendimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronSportsSyncRoute = ApiPublicCronSportsSyncRouteImport.update({
  id: '/api/public/cron/sports-sync',
  path: '/api/public/cron/sports-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksNetshopRoute =
  ApiPublicWebhooksNetshopRouteImport.update({
    id: '/api/public/webhooks/netshop',
    path: '/api/public/webhooks/netshop',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desportos': typeof DesportosRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/fish': typeof AuthenticatedFishRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/investidor/extrato': typeof AuthenticatedInvestidorExtratoRoute
  '/investidor/ordens': typeof AuthenticatedInvestidorOrdensRoute
  '/investidor/rendimentos': typeof AuthenticatedInvestidorRendimentosRoute
  '/investidor/': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/cron/sports-sync': typeof ApiPublicCronSportsSyncRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desportos': typeof DesportosRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/crash': typeof AuthenticatedCrashRoute
  '/fish': typeof AuthenticatedFishRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/investidor/extrato': typeof AuthenticatedInvestidorExtratoRoute
  '/investidor/ordens': typeof AuthenticatedInvestidorOrdensRoute
  '/investidor/rendimentos': typeof AuthenticatedInvestidorRendimentosRoute
  '/investidor': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/cron/sports-sync': typeof ApiPublicCronSportsSyncRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/desportos': typeof DesportosRoute
  '/empresas': typeof EmpresasRoute
  '/investimentos': typeof InvestimentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/crash': typeof AuthenticatedCrashRoute
  '/_authenticated/fish': typeof AuthenticatedFishRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/investidor/extrato': typeof AuthenticatedInvestidorExtratoRoute
  '/_authenticated/investidor/ordens': typeof AuthenticatedInvestidorOrdensRoute
  '/_authenticated/investidor/rendimentos': typeof AuthenticatedInvestidorRendimentosRoute
  '/_authenticated/investidor/': typeof AuthenticatedInvestidorIndexRoute
  '/api/public/cron/sports-sync': typeof ApiPublicCronSportsSyncRoute
  '/api/public/webhooks/netshop': typeof ApiPublicWebhooksNetshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/desportos'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/admin'
    | '/carteira'
    | '/crash'
    | '/fish'
    | '/kyc'
    | '/notificacoes'
    | '/investidor/extrato'
    | '/investidor/ordens'
    | '/investidor/rendimentos'
    | '/investidor/'
    | '/api/public/cron/sports-sync'
    | '/api/public/webhooks/netshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/desportos'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/admin'
    | '/carteira'
    | '/crash'
    | '/fish'
    | '/kyc'
    | '/notificacoes'
    | '/investidor/extrato'
    | '/investidor/ordens'
    | '/investidor/rendimentos'
    | '/investidor'
    | '/api/public/cron/sports-sync'
    | '/api/public/webhooks/netshop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/desportos'
    | '/empresas'
    | '/investimentos'
    | '/pagamentos'
    | '/_authenticated/admin'
    | '/_authenticated/carteira'
    | '/_authenticated/crash'
    | '/_authenticated/fish'
    | '/_authenticated/kyc'
    | '/_authenticated/notificacoes'
    | '/_authenticated/investidor/extrato'
    | '/_authenticated/investidor/ordens'
    | '/_authenticated/investidor/rendimentos'
    | '/_authenticated/investidor/'
    | '/api/public/cron/sports-sync'
    | '/api/public/webhooks/netshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DesportosRoute: typeof DesportosRoute
  EmpresasRoute: typeof EmpresasRoute
  InvestimentosRoute: typeof InvestimentosRoute
  PagamentosRoute: typeof PagamentosRoute
  ApiPublicCronSportsSyncRoute: typeof ApiPublicCronSportsSyncRoute
  ApiPublicWebhooksNetshopRoute: typeof ApiPublicWebhooksNetshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desportos': {
      id: '/desportos'
      path: '/desportos'
      fullPath: '/desportos'
      preLoaderRoute: typeof DesportosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crash': {
      id: '/_authenticated/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof AuthenticatedCrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fish': {
      id: '/_authenticated/fish'
      path: '/fish'
      fullPath: '/fish'
      preLoaderRoute: typeof AuthenticatedFishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investidor/': {
      id: '/_authenticated/investidor/'
      path: '/investidor'
      fullPath: '/investidor/'
      preLoaderRoute: typeof AuthenticatedInvestidorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investidor/extrato': {
      id: '/_authenticated/investidor/extrato'
      path: '/investidor/extrato'
      fullPath: '/investidor/extrato'
      preLoaderRoute: typeof AuthenticatedInvestidorExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investidor/ordens': {
      id: '/_authenticated/investidor/ordens'
      path: '/investidor/ordens'
      fullPath: '/investidor/ordens'
      preLoaderRoute: typeof AuthenticatedInvestidorOrdensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investidor/rendimentos': {
      id: '/_authenticated/investidor/rendimentos'
      path: '/investidor/rendimentos'
      fullPath: '/investidor/rendimentos'
      preLoaderRoute: typeof AuthenticatedInvestidorRendimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/sports-sync': {
      id: '/api/public/cron/sports-sync'
      path: '/api/public/cron/sports-sync'
      fullPath: '/api/public/cron/sports-sync'
      preLoaderRoute: typeof ApiPublicCronSportsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/netshop': {
      id: '/api/public/webhooks/netshop'
      path: '/api/public/webhooks/netshop'
      fullPath: '/api/public/webhooks/netshop'
      preLoaderRoute: typeof ApiPublicWebhooksNetshopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedCrashRoute: typeof AuthenticatedCrashRoute
  AuthenticatedFishRoute: typeof AuthenticatedFishRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedInvestidorExtratoRoute: typeof AuthenticatedInvestidorExtratoRoute
  AuthenticatedInvestidorOrdensRoute: typeof AuthenticatedInvestidorOrdensRoute
  AuthenticatedInvestidorRendimentosRoute: typeof AuthenticatedInvestidorRendimentosRoute
  AuthenticatedInvestidorIndexRoute: typeof AuthenticatedInvestidorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedCrashRoute: AuthenticatedCrashRoute,
  AuthenticatedFishRoute: AuthenticatedFishRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedInvestidorExtratoRoute: AuthenticatedInvestidorExtratoRoute,
  AuthenticatedInvestidorOrdensRoute: AuthenticatedInvestidorOrdensRoute,
  AuthenticatedInvestidorRendimentosRoute:
    AuthenticatedInvestidorRendimentosRoute,
  AuthenticatedInvestidorIndexRoute: AuthenticatedInvestidorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DesportosRoute: DesportosRoute,
  EmpresasRoute: EmpresasRoute,
  InvestimentosRoute: InvestimentosRoute,
  PagamentosRoute: PagamentosRoute,
  ApiPublicCronSportsSyncRoute: ApiPublicCronSportsSyncRoute,
  ApiPublicWebhooksNetshopRoute: ApiPublicWebhooksNetshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
